<block>         ::= (<assign> | <func_call> | <keyword>)*

<keyword>       ::= <if_statement>
<if_statement>  ::= if <conditional> then <block> (else <block>)? endif
<assign>        ::= <ident> "=" <root_expr>
<root_expr>     ::= <expr> | <conditional>
<expr>          ::= <term> "+" <expr> | <term> "-" <expr> | <term>
<conditional>   ::= <expr> <condition> <expr>
<condition>     ::= ">" | ">=" | "<" | "<="
<term>          ::= <factor> "*" <term> | <factor> "/" <term> | <factor>
<factor>        ::= NUMBER | <ident> | "(" <expr> ")" | <func_call>

<func_call>     ::= <ident> "(" <arg> ("," <arg>)* ")"
<arg>           ::= <root_expr> | <string>

<string>        ::= " STRING "
<ident>         ::= STRING
